line-length = 100
target-version = "py38"
extend-exclude = ["__init__.py"]

[lint]
extend-select = ["E", "F", "UP", "SIM", "I", "Q", "RUF100"]
typing-modules = ["airflow.typing_compat"]
ignore = ["F631"]

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint.pycodestyle]
ignore-overlong-task-comments = true
max-line-length = 320
